logging:
  console:
    # For a MCP stdio server, we don't want to log to the console, See https://modelcontextprotocol.io/docs/develop/build-server#logging-in-mcp-servers-3
    enabled: false
  file:
    name: accuweather-mcp.log
    
spring:
  application:
    name: accuweather-mcp
  main:
    # For a MCP stdio server, we don't want to log to the console, See https://modelcontextprotocol.io/docs/develop/build-server#logging-in-mcp-servers-3
    banner-mode: off
  ai:
    mcp:
      server:
        name: accuweather-mcp
        version: ${APP_VERSION:local-SNAPSHOT}
        instructions: "This server provides weather information sourced from AccuWeather."
        type: SYNC
        stdio: true
        capabilities:
          completion: true
          resource: false
          tool: true
          prompt: true

  http:
    serviceclient:
      accuweather:
        base-url: https://dataservice.accuweather.com
        default-header:
          Accept-Encoding: gzip,deflate
          Authorization: Bearer ${ACCUWEATHER_API_KEY}