spring:
  application:
    name: weathermcp
  ai:
    mcp:
      server:
        name: weathermcp
        version: ${APP_VERSION:0.0.1-SNAPSHOT}
        type: SYNC
        stdio: true
  http:
    serviceclient:
      accuweather:
        base-url: https://dataservice.accuweather.com
        api-key: "CHANGE_ME"

        # TODO sort out default headers of GZIP and authentication